# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
   deploy:
     environment:
       name: github-pages
       url: ${{ steps.deployment.outputs.page_url }}
     runs-on: ubuntu-latest
     steps:
       # on récupère le code du git sur le runneer
       - name: Checkout
         uses: actions/checkout@v4
       - name: check checkout
         run: ls
      # - name: 📂 Sync files
        # uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        # with:
          # server: ${{ secrets.FTP_URL }}
          # username: ${{ secrets.FTP_USER }}
          # password: ${{ secrets.FTP_PASS }}
          # server-dir: www/dwwm/
          # exclude: |
            # **/.git*
            # **/.git*/**
            # README.md

      
